services:
    api:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./src:/usr/src/app/src
        container_name: api

    pg:
        image: postgres:17
        ports:
            - 5432:5432
        container_name: fueltix-database
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dba_password
            POSTGRES_DB: fueltix
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
