services:
    api:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./src:/usr/src/app/src
        container_name: api
        depends_on:
            mssql:
                condition: service_healthy

    mssql:
        user: root
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: '@admin123'
            MSSQL_PID: 'Developer'
            MSSQL_USER: 'sa'
        container_name: mssql
        healthcheck:
            # do not use sqlcmd as it is not available in the image
            test: ['CMD', 'curl', '-s', '-f', 'http://localhost:1433']
            interval: 15s
            retries: 5
            start_period: 30s
